### ISSUE TITLE
i start the app but it shows up for a second and then it goes away

### ISSUE THREAD

**Issue by KAR-M-an** [zephyrj/engine-crane#15]
So as i said 
on youtube i wanted to use the app but the command prompt and the app just flash for a second and then vanish i tried disabling the antivirus and moving the app and all of it's files to other folders like my documents and downloads but still the same issue so i will attach the log file to see if maybe the log can say something about what i'm doing wrong
[engine_crane.log](https://github.com/zephyrj/engine-crane/files/10582966/engine_crane.log)

**Comment by zephyrj** [comment]
Hi,

I've just created a new release that has re-jigged the way it starts-up and should hopefully add some more logging in to help diagose issues. Would you be able to give it a try?
[engine-crane-0.1.15](https://github.com/zephyrj/engine-crane/releases/download/v0.1.15-alpha/engine-crane-windows-0_1_15-alpha.7z)

Please run it from a completely empty folder so that it doesn't try to pick anything up from previous versions.

If it crashes again could you please send me the log file and I'll go through it and hopefully have some more info to go on

**Comment by KAR-M-an** [comment]
so after i got this new version it still does not work but the log file is different from the log file that was in the last version, now the log file says that it Initialised settings successfully, that it created settings tab, that it created engine-swap taband that it launched the ui and before it was just showing that it found where beamng mods are, where the assetto install path is, how many mods beamng has from automation and how many assetto corsa cars i have. 
So after all that i guess it's better but still not working (and sorry for probably giving you a bunch of headaches for a problem that totally is just because my system is from 2011) oh yeah and i attached the log file too 
[engine_crane.log](https://github.com/zephyrj/engine-crane/files/10714582/engine_crane.log)

**Comment by zephyrj** [comment]
Damn, that's frustrating. It might be the library I'm using for the UI that's throwing an error and that's mostly out of my control. I'll have another look this evening (currently visiting family) to see if there is anything else I can look into.

Would you be able to let me know the following details:
- Windows version (7, 10, 11 etc)
- The CPU and Graphics card you're using.

**Comment by KAR-M-an** [comment]
i have window 10 pro and im rocking a i7-2670QM and a nvidia geforce gt 630m (2gb version)

**Comment by zephyrj** [comment]
I've created a new debug build of engine-crane for you to try. Could you please try the following instructions?

- Download https://github.com/zephyrj/engine-crane/releases/download/v0.1.15-alpha/engine-crane-windows-debug-0_1_15-alpha.7z
- Extract it somewhere, then open up that location in a explorer window
- In the menu bar at the top (where it shows you the folder path you are in) type `cmd`
- You will see a command-line prompt. Enter the following command and press enter:
  -  `set RUST_BACKTRACE=full`
- Then run engine-crane by typing:
  -  `engine-crane.exe`

I'm interested to see if anything is printed to the command-line. If it is would you be able to send it to me please?

**Comment by zephyrj** [comment]
I've also think I may have found a potential incompatability with older graphics cards in the GUI library I've been using. I've reconfigured how I use that lib so that may also solve your issue. 

I've released a new version with the changes in here:
https://github.com/zephyrj/engine-crane/releases/download/v0.1.16-alpha/engine-crane-windows-0_1_16-alpha.7z

**Comment by KAR-M-an** [comment]
ooooh finally, thank you very very much, i tried the debug and it said nothing in the command prompt but now when i tried the new version it finally works, thank you very much again, i can finally put my engines in assetto
