### ISSUE TITLE
no cars in beamng dropdown

### ISSUE THREAD

**Issue by cupcakeman202** [zephyrj/engine-crane#25]
when i went to use beamng drop down (i have it set the mod path) there is no cars available i dont know what to do please help me

**Comment by zephyrj** [comment]
Hi, 

BeamNG mods must be zip-packed for them to be picked up by engine-crane so make sure that the zip-pack option is selected when creating the mod in Automation - this used to be the default option but since the Ellisbury update I think it now defaults to not zip-packing them.

Once I've completed work on the 0.3 release I'll try to get it to pick up BeamNG mods that aren't zip-packed too to make this easier to work with in future

**Comment by cupcakeman202** [comment]
my brain struggled to comprehend what you said can you post a tutorial

**Comment by cupcakeman202** [comment]
thanks so much.

**Comment by zephyrj** [comment]
If that has solved your issue are you happy for me to close this issue?
